version: '3.8'

services:
  postgres:
    image: postgres:16        # official PostgresSQL image
    container_name: elt_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elt_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # the actual database storage, database persists on machine
      - ./data:/data          # mounts datasets inside the container
      - ./scripts:/scripts    # mount scripts folder
    restart: unless-stopped