CREATE SCHEMA IF NOT EXISTS gold;

DROP TABLE IF EXISTS gold.column_dictionary;

CREATE TABLE gold.column_dictionary (
  column_name           text PRIMARY KEY,
  source_table          text,         -- e.g. silver.land_registry_quarterly
  original_label        text,         -- original source column or MLAR category
  source_marker         text,         -- e.g. MLAR.1.21.C.1 or LPMB3C8
  unit_original         text,         -- original unit (e.g., '£m', '%', 'count')
  unit_normalized       text,         -- normalized unit in gold (e.g., 'gbp', '%', 'count')
  transformation        text,         -- short note about conversion (e.g., 'x1e6', 'NULLIF->cast')
  description           text,
  example_value         text,
  notes                 text
);

INSERT INTO gold.column_dictionary VALUES
('quarter_start__date',
 'silver.land_registry_quarterly',
 'quarter_start',
 NULL,
 'date',
 'date',
 'none',
 'Canonical quarter start (first day of quarter)',
 '2007-01-01',
 NULL),

('transactions_total__LR__count',
 'silver.land_registry_quarterly',
 'total_transactions',
 'LR',
 'count',
 'count',
 'none',
 'Number of property transactions in quarter (Land Registry)',
 '172668',
 'aggregated from bronze.land_registry_raw'),

('price_avg__LR__gbp',
 'silver.land_registry_quarterly',
 'avg_price',
 'LR',
 'gbp',
 'gbp',
 'none',
 'Average property price in quarter (GBP)',
 '66496.64',
 NULL),

('price_median__LR__gbp',
 'silver.land_registry_quarterly',
 'median_price',
 'LR',
 'gbp',
 'gbp',
 'none',
 'Median property price in quarter (GBP)',
 '53500.00',
 NULL),

('boe_total_secured_lending__LPMB3C8__count',
 'silver.boe_monthly_clean',
 'total_secured_lending (aggregated to quarter)',
 'LPMB3C8',
 'count',
 'count',
 'SUM(monthly) over quarter',
 'Total secured lending approvals (BOE) — quarterly sum',
 '111963',
 NULL),

('boe_total_remortgage__LPMB4B3__count',
 'silver.boe_monthly_clean',
 'total_remortgage (aggregated to quarter)',
 'LPMB4B3',
 'count',
 'count',
 'SUM(monthly) over quarter',
 'Remortgage approvals — quarterly sum',
 '38103',
 NULL),

('boe_total_other_lending__LPMB4B4__count',
 'silver.boe_monthly_clean',
 'total_other_lending (aggregated to quarter)',
 'LPMB4B4',
 'count',
 'count',
 'SUM(monthly) over quarter',
 'Other secured lending approvals — quarterly sum',
 '13860',
 NULL),

('boe_house_purchase__LPMVTVX__count',
 'silver.boe_monthly_clean',
 'total_house_purchase (aggregated to quarter)',
 'LPMVTVX',
 'count',
 'count',
 'SUM(monthly) over quarter',
 'House purchase approvals — quarterly sum',
 '59999',
 NULL),

('boe_mfi_total_approvals__LPMZ3UP__count',
 'silver.boe_monthly_clean',
 'mfi_total_approvals (aggregated to quarter)',
 'LPMZ3UP',
 'count',
 'count',
 'SUM(monthly) over quarter',
 'Total MFI approvals — quarterly sum',
 '108292',
 NULL),

('mlar_gross_advances__MLAR.1.21.C.1__gbp',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - Business flows - Gross advances',
 'MLAR.1.21.C.1',
 'gbp_mn',
 'gbp',
 'value * 1000000',
 'Gross advances (normalized to GBP)',
 '73139020000.00',
 'originally in £ millions — normalized to £'),

('mlar_net_advances__MLAR.1.21.C.2__gbp',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - Business flows - Net advances',
 'MLAR.1.21.C.2',
 'gbp_mn',
 'gbp',
 'value * 1000000',
 'Net advances (normalized to GBP)',
 '61301074000.00',
 'originally in £ millions — normalized to £'),

('mlar_new_commitments__MLAR.1.21.C.3__gbp',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - Business flows - New commitments',
 'MLAR.1.21.C.3',
 'gbp_mn',
 'gbp',
 'value * 1000000',
 'New commitments (normalized to GBP)',
 '81996015000.00',
 'originally in £ millions — normalized to £'),

('mlar_imp_repayment__MLAR.1.32.C.3__pct',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - With Impaired credit history - Advances - Repayment (capital + interest)',
 'MLAR.1.32.C.3',
 '%',
 '%',
 'none (numeric)',
 'Impaired loans share: repayment advances (%)',
 '3.745',
 NULL),

('mlar_imp_interest_only__MLAR.1.32.C.4__pct',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - With Impaired credit history - Advances - Interest only',
 'MLAR.1.32.C.4',
 '%',
 '%',
 'none (numeric)',
 'Impaired loans share: interest-only advances (%)',
 '3.786',
 NULL),

('mlar_imp_combined__MLAR.1.32.C.5__pct',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - With Impaired credit history - Advances - Combined',
 'MLAR.1.32.C.5',
 '%',
 '%',
 'none (numeric)',
 'Impaired loans share: combined advances (%)',
 '4.016',
 NULL),

('mlar_imp_other__MLAR.1.32.C.6__pct',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - With Impaired credit history - Advances - Other',
 'MLAR.1.32.C.6',
 '%',
 '%',
 'none (numeric)',
 'Impaired loans share: other advances (%)',
 '3.599',
 NULL),

('mlar_new_house_purchase__MLAR.1.33.C.29__gbp',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - New commitments in quarter - Amounts by purpose - House purchase',
 'MLAR.1.33.C.29',
 'gbp_mn',
 'gbp',
 'value * 1000000',
 'New commitments for house purchase (normalized to GBP)',
 '40000000000.00',
 'originally in £ millions — normalized to £'),

('mlar_new_remortgage__MLAR.1.33.C.30__gbp',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - New commitments in quarter - Amounts by purpose - Remortgage',
 'MLAR.1.33.C.30',
 'gbp_mn',
 'gbp',
 'value * 1000000',
 'New commitments for remortgage (normalized to GBP)',
 '30000000000.00',
 'originally in £ millions — normalized to £'),

('mlar_new_other__MLAR.1.33.C.31__gbp',
 'silver.mlar_long',
 'All (Regulated and Non-regulated) - New commitments in quarter - Amounts by purpose - Other (inc further advances)',
 'MLAR.1.33.C.31',
 'gbp_mn',
 'gbp',
 'value * 1000000',
 'New commitments for other purposes (normalized to GBP)',
 '10000000000.00',
 'originally in £ millions — normalized to £'),

('dq_boe_nulls_count__meta',
 NULL,NULL,NULL,NULL,NULL,'count NULLs across key BOE vars','Number of BOE numeric NULLs aggregated for the quarter','2',NULL),

('dq_mlar_nulls_count__meta',
 NULL,NULL,NULL,NULL,NULL,'count NULLs across selected MLAR metrics','Number of MLAR numeric NULLs for the quarter','1',NULL),

('source_available_lr__flag',
 NULL,NULL,NULL,NULL,NULL,'bool','Is Land Registry source present for this quarter?','true',NULL),

('source_available_boe__flag',
 NULL,NULL,NULL,NULL,NULL,'bool','Is BOE source present for this quarter?','true',NULL),

('source_available_mlar__flag',
 NULL,NULL,NULL,NULL,NULL,'bool','Is MLAR source present for this quarter?','true',NULL)
;